#!/bin/bash

set -eu

function info {
  echo "[INFO] $*"
}

function error {
  echo "[ERROR] $*"
}

info 'Starting update of pom.xml version to release...'

# Get current maven version.
version=$(./mvn-current-version)
info "Current Version: $version"

release_version=$(echo "$version" | perl -p -e 's/-SNAPSHOT$//')
info "Release Version: $release_version"

if [ "${version}" = "${release_version}" ]; then
  error 'This is not a snapshot, aborting!'
  exit 42
fi

info "Setting version in pom.xml to ${release_version}"
exec mvn --quiet versions:set -DnewVersion="${release_version}"

info 'Success!'

# EOF
