#!/bin/bash

set -eu

top_dir=$(dirname "$0")

function info {
  echo "[INFO] $*"
}

function error {
  echo "[ERROR] $*"
}

info 'Starting update of pom.xml version to release...'

# Get current maven version.
version=$("${top_dir}/mvn-current-version")
info "Current Version: $version"

release_version=$(echo "$version" | perl -p -e 's/-SNAPSHOT$//')
info "Release Version: $release_version"

if [ "${version}" = "${release_version}" ]; then
  error 'This is not a snapshot, aborting!'
  exit 42
fi

info 'Success!'

# EOF
